# TODO require puppet-lint
rvm: 1.8.7
branches:
  only:
    - master
notifications:
  email:
    - palladius@github.com
    - rusko@palladius.it
env:
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.11
